package com.pribantsa.rrhh.model;
// Generated 08-10-2016 09:57:07 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento")
public class Departamento implements java.io.Serializable {

	private Long idDepartamento;
	private String nombre;
	private String descripcion;
	private Set<Empleado> empleados = new HashSet<Empleado>(0);
	private Set<Objdepartamento> objdepartamentos = new HashSet<Objdepartamento>(0);

	public Departamento() {
	}

	public Departamento(Long idDepartamento, String nombre, String descripcion) {
		this.idDepartamento = idDepartamento;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Departamento(Long idDepartamento, String nombre, String descripcion, Set<Empleado> empleados,
			Set<Objdepartamento> objdepartamentos) {
		this.idDepartamento = idDepartamento;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.empleados = empleados;
		this.objdepartamentos = objdepartamentos;
	}

	@Id

	@Column(name = "id_departamento", unique = true, nullable = false)
	public Long getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(Long idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Objdepartamento> getObjdepartamentos() {
		return this.objdepartamentos;
	}

	public void setObjdepartamentos(Set<Objdepartamento> objdepartamentos) {
		this.objdepartamentos = objdepartamentos;
	}

}
