package com.pribantsa.rrhh.model;
// Generated 08-10-2016 09:57:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Descuento generated by hbm2java
 */
@Entity
@Table(name = "descuento", schema = "pribantsa")
public class Descuento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6472391473383832440L;
	private int idDescuento;
	private Empleado empleado;
	private TipoDescuento tipoDescuento;
	private Date fecha;

	public Descuento() {
	}

	public Descuento(int idDescuento, Empleado empleado, TipoDescuento tipoDescuento, Date fecha) {
		this.idDescuento = idDescuento;
		this.empleado = empleado;
		this.tipoDescuento = tipoDescuento;
		this.fecha = fecha;
	}

	@Id

	@Column(name = "idDescuento", nullable = false)
	public int getIdDescuento() {
		return this.idDescuento;
	}

	public void setIdDescuento(int idDescuento) {
		this.idDescuento = idDescuento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpleado", nullable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoDescuento", nullable = false)
	public TipoDescuento getTipoDescuento() {
		return this.tipoDescuento;
	}

	public void setTipoDescuento(TipoDescuento tipoDescuento) {
		this.tipoDescuento = tipoDescuento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
