package com.pribantsa.rrhh.model;
// Generated 08-10-2016 09:57:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Educacion generated by hbm2java
 */
@Entity
@Table(name = "educacion", schema = "pribantsa")
public class Educacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8663721827534845004L;
	private int idEducacion;
	private Empleado empleado;
	private String titulo;
	private Date fecha;
	private String lugar;
	private String institucion;
	private String idx;
	private String nivel;

	public Educacion() {
	}

	public Educacion(int idEducacion, String titulo, Date fecha) {
		this.idEducacion = idEducacion;
		this.titulo = titulo;
		this.fecha = fecha;
	}

	public Educacion(int idEducacion, Empleado empleado, String titulo, Date fecha, String lugar, String institucion,
			String idx, String nivel) {
		this.idEducacion = idEducacion;
		this.empleado = empleado;
		this.titulo = titulo;
		this.fecha = fecha;
		this.lugar = lugar;
		this.institucion = institucion;
		this.idx = idx;
		this.nivel = nivel;
	}

	@Id

	@Column(name = "id_educacion", unique = true, nullable = false)
	public int getIdEducacion() {
		return this.idEducacion;
	}

	public void setIdEducacion(int idEducacion) {
		this.idEducacion = idEducacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_estudios")
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "titulo", nullable = false)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "lugar")
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Column(name = "institucion")
	public String getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(String institucion) {
		this.institucion = institucion;
	}

	@Column(name = "idx")
	public String getIdx() {
		return this.idx;
	}

	public void setIdx(String idx) {
		this.idx = idx;
	}

	@Column(name = "nivel")
	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

}
