package com.pribantsa.rrhh.model;
// Generated 08-10-2016 09:57:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExpLaboral generated by hbm2java
 */
@Entity
@Table(name = "exp_laboral")
public class ExpLaboral implements java.io.Serializable {

	private long idExplaboral;
	private Empleado empleado;
	private String lugar;
	private Integer tiempo;
	private String cargo;
	private Integer idx;

	public ExpLaboral() {
	}

	public ExpLaboral(long idExplaboral) {
		this.idExplaboral = idExplaboral;
	}

	public ExpLaboral(long idExplaboral, Empleado empleado, String lugar, Integer tiempo, String cargo, Integer idx) {
		this.idExplaboral = idExplaboral;
		this.empleado = empleado;
		this.lugar = lugar;
		this.tiempo = tiempo;
		this.cargo = cargo;
		this.idx = idx;
	}

	@Id

	@Column(name = "id_explaboral", unique = true, nullable = false)
	public long getIdExplaboral() {
		return this.idExplaboral;
	}

	public void setIdExplaboral(long idExplaboral) {
		this.idExplaboral = idExplaboral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpleado")
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "lugar")
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Column(name = "tiempo")
	public Integer getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(Integer tiempo) {
		this.tiempo = tiempo;
	}

	@Column(name = "cargo")
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "idx")
	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

}
