package com.pribantsa.rrhh.model;
// Generated 08-10-2016 09:57:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Objdepartamento generated by hbm2java
 */
@Entity
@Table(name = "objdepartamento")
public class Objdepartamento implements java.io.Serializable {

	private long idObjetivodep;
	private Departamento departamento;
	private String tipo;
	private String descripcion;
	private Integer idx;

	public Objdepartamento() {
	}

	public Objdepartamento(long idObjetivodep) {
		this.idObjetivodep = idObjetivodep;
	}

	public Objdepartamento(long idObjetivodep, Departamento departamento, String tipo, String descripcion,
			Integer idx) {
		this.idObjetivodep = idObjetivodep;
		this.departamento = departamento;
		this.tipo = tipo;
		this.descripcion = descripcion;
		this.idx = idx;
	}

	@Id

	@Column(name = "id_objetivodep", unique = true, nullable = false)
	public long getIdObjetivodep() {
		return this.idObjetivodep;
	}

	public void setIdObjetivodep(long idObjetivodep) {
		this.idObjetivodep = idObjetivodep;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_departamento")
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "idx")
	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

}
