package com.pribantsa.rrhh.model;
// Generated 08-10-2016 09:57:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Objetivo generated by hbm2java
 */
@Entity
@Table(name = "objetivo", schema = "pribantsa")
public class Objetivo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7928601453035558399L;
	private int idObjetivo;
	private PuestoTrabajo puestoTrabajo;
	private String funcion;
	private Integer idx;

	public Objetivo() {
	}

	public Objetivo(int idObjetivo, String funcion) {
		this.idObjetivo = idObjetivo;
		this.funcion = funcion;
	}

	public Objetivo(int idObjetivo, PuestoTrabajo puestoTrabajo, String funcion, Integer idx) {
		this.idObjetivo = idObjetivo;
		this.puestoTrabajo = puestoTrabajo;
		this.funcion = funcion;
		this.idx = idx;
	}

	@Id

	@Column(name = "id_objetivo", unique = true, nullable = false)
	public int getIdObjetivo() {
		return this.idObjetivo;
	}

	public void setIdObjetivo(int idObjetivo) {
		this.idObjetivo = idObjetivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpuesto_trabajo")
	public PuestoTrabajo getPuestoTrabajo() {
		return this.puestoTrabajo;
	}

	public void setPuestoTrabajo(PuestoTrabajo puestoTrabajo) {
		this.puestoTrabajo = puestoTrabajo;
	}

	@Column(name = "funcion", nullable = false)
	public String getFuncion() {
		return this.funcion;
	}

	public void setFuncion(String funcion) {
		this.funcion = funcion;
	}

	@Column(name = "idx")
	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

}
