package com.pribantsa.rrhh.model;
// Generated 08-10-2016 09:57:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name = "telefono", schema = "pribantsa")
public class Telefono implements java.io.Serializable {

	private int idTelefono;
	private Empleado empleado;
	private String telefono;

	public Telefono() {
	}

	public Telefono(int idTelefono, Empleado empleado, String telefono) {
		this.idTelefono = idTelefono;
		this.empleado = empleado;
		this.telefono = telefono;
	}

	@Id

	@Column(name = "idTelefono", nullable = false)
	public int getIdTelefono() {
		return this.idTelefono;
	}

	public void setIdTelefono(int idTelefono) {
		this.idTelefono = idTelefono;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpleado", nullable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "telefono", nullable = false)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
