package com.pribantsa.rrhh.model;
// Generated 08-10-2016 09:57:07 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContrato generated by hbm2java
 */
@Entity
@Table(name = "tipo_contrato")
public class TipoContrato implements java.io.Serializable {

	private int idTipoContrato;
	private String descripcion;
	private Set<Contrato> contratos = new HashSet<Contrato>(0);

	public TipoContrato() {
	}

	public TipoContrato(int idTipoContrato, String descripcion) {
		this.idTipoContrato = idTipoContrato;
		this.descripcion = descripcion;
	}

	public TipoContrato(int idTipoContrato, String descripcion, Set<Contrato> contratos) {
		this.idTipoContrato = idTipoContrato;
		this.descripcion = descripcion;
		this.contratos = contratos;
	}

	@Id

	@Column(name = "idTipoContrato", nullable = false)
	public int getIdTipoContrato() {
		return this.idTipoContrato;
	}

	public void setIdTipoContrato(int idTipoContrato) {
		this.idTipoContrato = idTipoContrato;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContrato")
	public Set<Contrato> getContratos() {
		return this.contratos;
	}

	public void setContratos(Set<Contrato> contratos) {
		this.contratos = contratos;
	}

}
